[tool.black]
line-length = 120
skip-magic-trailing-comma = true

[tool.flake8]
max-line-length = 120
ignore = ["E203", "E266", "E501", "W503"]
exclude = [".git", "__pycache__", "venv"]
per-file-ignores = ["*/__init__.py: F401"]

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = false
